package rechard.learn.springboot.entity;

import java.math.BigDecimal;

public class Good {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..goods.id
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..goods.goods_name
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..goods.goods_title
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private String goodsTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..goods.goods_img
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..goods.goods_price
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..goods.goods_stock
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private Integer goodsStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..goods.goods_detail
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private String goodsDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..goods.id
     *
     * @return the value of miaosha..goods.id
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..goods.id
     *
     * @param id the value for miaosha..goods.id
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..goods.goods_name
     *
     * @return the value of miaosha..goods.goods_name
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..goods.goods_name
     *
     * @param goodsName the value for miaosha..goods.goods_name
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..goods.goods_title
     *
     * @return the value of miaosha..goods.goods_title
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..goods.goods_title
     *
     * @param goodsTitle the value for miaosha..goods.goods_title
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..goods.goods_img
     *
     * @return the value of miaosha..goods.goods_img
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..goods.goods_img
     *
     * @param goodsImg the value for miaosha..goods.goods_img
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..goods.goods_price
     *
     * @return the value of miaosha..goods.goods_price
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..goods.goods_price
     *
     * @param goodsPrice the value for miaosha..goods.goods_price
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..goods.goods_stock
     *
     * @return the value of miaosha..goods.goods_stock
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public Integer getGoodsStock() {
        return goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..goods.goods_stock
     *
     * @param goodsStock the value for miaosha..goods.goods_stock
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setGoodsStock(Integer goodsStock) {
        this.goodsStock = goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..goods.goods_detail
     *
     * @return the value of miaosha..goods.goods_detail
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public String getGoodsDetail() {
        return goodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..goods.goods_detail
     *
     * @param goodsDetail the value for miaosha..goods.goods_detail
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setGoodsDetail(String goodsDetail) {
        this.goodsDetail = goodsDetail;
    }
}