package rechard.learn.springboot.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..user.id
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..user.tel
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private Long tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..user.nickname
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..user.password
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..user.salt
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..user.head
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private String head;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..user.register_date
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..user.last_login_date
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private Date lastLoginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha..user.login_count
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    private Integer loginCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..user.id
     *
     * @return the value of miaosha..user.id
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..user.id
     *
     * @param id the value for miaosha..user.id
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..user.tel
     *
     * @return the value of miaosha..user.tel
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public Long getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..user.tel
     *
     * @param tel the value for miaosha..user.tel
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setTel(Long tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..user.nickname
     *
     * @return the value of miaosha..user.nickname
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..user.nickname
     *
     * @param nickname the value for miaosha..user.nickname
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..user.password
     *
     * @return the value of miaosha..user.password
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..user.password
     *
     * @param password the value for miaosha..user.password
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..user.salt
     *
     * @return the value of miaosha..user.salt
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..user.salt
     *
     * @param salt the value for miaosha..user.salt
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..user.head
     *
     * @return the value of miaosha..user.head
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..user.head
     *
     * @param head the value for miaosha..user.head
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setHead(String head) {
        this.head = head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..user.register_date
     *
     * @return the value of miaosha..user.register_date
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..user.register_date
     *
     * @param registerDate the value for miaosha..user.register_date
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..user.last_login_date
     *
     * @return the value of miaosha..user.last_login_date
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..user.last_login_date
     *
     * @param lastLoginDate the value for miaosha..user.last_login_date
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha..user.login_count
     *
     * @return the value of miaosha..user.login_count
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha..user.login_count
     *
     * @param loginCount the value for miaosha..user.login_count
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }
}