package rechard.learn.springboot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import rechard.learn.springboot.entity.Good;
import rechard.learn.springboot.entity.GoodExample;

public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    long countByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int deleteByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int insertSelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    List<Good> selectByExampleWithBLOBs(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    List<Good> selectByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    Good selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int updateByExample(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int updateByPrimaryKeySelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha..goods
     *
     * @mbg.generated Sun May 12 15:39:15 CST 2019
     */
    int updateByPrimaryKey(Good record);
}